# .github/workflows/ci-release.yml
name: CI & Release

on:
  push:
    branches:      # Trigger on pushes to master
      - master
    tags:          # Trigger on semver tags
      - 'v*.*.*'

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'    # Install .NET 8 SDK (covers netstandard2.0 too)

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore -c Release

      - name: Run tests
        run: dotnet test  --no-build    -c Release

  pack:
    needs: build-and-test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Pack NuGet package
        run: |
          dotnet pack src/QuickXL.Core/QuickXL.Core.csproj \
            -c Release \
            -o ./nupkg

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: QuickXL-nupkg
          path: ./nupkg/*.nupkg

  publish-nuget:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: pack
    runs-on: ubuntu-latest
    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: QuickXL-nupkg

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Publish to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push ./nupkg/*.nupkg \
            --api-key $NUGET_API_KEY \
            --source https://api.nuget.org/v3/index.json

  create-github-release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: publish-nuget
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            - 🎉 Added multi-target support: net8.0 & netstandard2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
